### ISSUE TITLE
Add FAQ entry on copying and pasting from mintty and customising it

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GapWWW#100]
There should be an explanation with screenshots, to which the users can be referred.

**Comment by alex-konovalov** [comment]
Also emphasise how to start GAP on Windows - bat files, not exe (also, investigate, why exe does not work - maybe layout of dlls should be changed to allow this, like under Linux?)

**Comment by alex-konovalov** [comment]
Made a collection of screenshots, next step is to describe them in mixer.

### customising mintty

Click on the monitor pictogram in the corner of the terminal, then click on "Options"

![1](https://user-images.githubusercontent.com/5751387/45427652-47758080-b697-11e8-81a2-6784cb49cf7a.png)

Use "Looks" tab to set up colours of the font and the background:

![2](https://user-images.githubusercontent.com/5751387/45427653-480e1700-b697-11e8-9d68-142f6bf0c331.png)

Use "Text" tab to set up font size:

![3](https://user-images.githubusercontent.com/5751387/45427654-480e1700-b697-11e8-9d6c-5555859093e0.png)

Use "Keys" tab to learn which keyboard shortcuts are available:
 
![4](https://user-images.githubusercontent.com/5751387/45427655-480e1700-b697-11e8-90ad-5b531d9880c5.png)

Use "Mouse" tab to configure mouse behaviour: 
![5](https://user-images.githubusercontent.com/5751387/45427658-493f4400-b697-11e8-972d-ebab04aca450.png)

## copying and pasting

For example, if this is a text that you want to copy

![6](https://user-images.githubusercontent.com/5751387/45427661-49d7da80-b697-11e8-9645-074cf7013b0e.png)

then you can select it with mouse

![7](https://user-images.githubusercontent.com/5751387/45427662-49d7da80-b697-11e8-98ce-f85b92d5a520.png)

But default, "copy on select" is on (see above on the "mouse" tab), so the text will be immediately copied into a buffer. Now you should be able to paste it elsewhere.

To paste the text from the buffer,  in the default setting clicking on the right mouse button reveals a context menu (and also reminds of keyboard shortcuts):

![8](https://user-images.githubusercontent.com/5751387/45427663-49d7da80-b697-11e8-89fb-dc294ca523d0.png)

**Comment by fingolfin** [comment]
Is this still a common issue? Wonder what @ChrisJefferson thinks about it?

**Comment by ChrisJefferson** [comment]
These things still exist, but I'm not sure it's worth us explictly explaining them, when they are general terminal things -- searching for cut+paste in terminal generally will find the cut+paste instructions.

**Comment by olexandr-konovalov** [comment]
Yes, let's close this.
