### ISSUE TITLE
gap monoid page exists, but is broken

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-system/GapWWW#11]
Googling for 'gap monoid' finds this page:

www.gap-system.org/Packages/monoid.html

Which is not linked to from anywhere, and is full of broken links (and is for a now-removed package)

**Comment by alex-konovalov** [comment]
Thanks. One should then delete https://github.com/gap-system/GapWWW/blob/master/Packages/monoid.mixer - will do this while the coming update.

**Comment by alex-konovalov** [comment]
I left the page there, but instead of the broken links it contains only a link to Semigroups package which supersedes MONOID. Just in case if the link is e.g. in some paper citing MONOID.
