### ISSUE TITLE
Add to GAP citations Submission to the NIST LWC Competition

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GapWWW#117]
GAP used in [WAGE: An Authenticated CipherSubmission to the NIST LWC Competition](https://csrc.nist.gov/CSRC/media/Projects/Lightweight-Cryptography/documents/round-1/spec-doc/wage-spec.pdf
) by Mark Aagaard, Riham AlTawy, Guang Gong, Kalikinkar Mandal, Raghvendra Rohit, and Nusa Zidaric (H/T @nzidaric - thanks!). 

Background:
- [Call for submissions](https://csrc.nist.gov/CSRC/media/Projects/Lightweight-Cryptography/documents/final-lwc-submission-requirements-august2018.pdf)
- [Round 1 Candidates](https://csrc.nist.gov/Projects/Lightweight-Cryptography/Round-1-Candidates)

**Comment by alex-konovalov** [comment]
Also add the PhD thesis by @nzidaric:

Nusa Zidaric (2020). Automated Design Space Exploration and Datapath Synthesis for Finite Field Arithmetic with Applications to Lightweight Cryptography. UWSpace. http://hdl.handle.net/10012/15928

**Comment by fingolfin** [comment]
We don't track PhD theses anymore.

If the funding is supposed to be acknowledged, then @nzidaric or anyone else is of course highly welcome to edit https://www.gap-system.org/about/#funding suitable via the "Edit this page" button to create a PR with the relevant change. I am also happy to assist with that if there are any trouble.
