### ISSUE TITLE
correct reference/corrigendum to MR3741064

### ISSUE THREAD

**Issue by dimpase** [gap-system/GapWWW#120]
as communicated to us on gap-support:
correct a reference you are quoting in this two links:
https://mathscinet.ams.org/mathscinet-getitem?mr=3741064 and https://www.gap-system.org/Doc/Bib/MSC/12.html
Algebraic certification of numerical algorithms computing
Lagrange resolvents, J. Algebra Appl., 17 (1) (2018), 1850007,
15.

The corrigendum and the right reference of JAA is given in this link : https://www.worldscientific.com/doi/10.1142/S0219498819920014

**Comment by dimpase** [comment]
not yet on mathscinet; running doi2bib gives
```
@article{Abdeljaoued_Tej_2019,
	doi = {10.1142/s0219498819920014},
	url = {https://doi.org/10.1142%2Fs0219498819920014},
	year = 2019,
	month = {feb},
	publisher = {World Scientific Pub Co Pte Lt},
	pages = {1992001},
	author = {Ines Abdeljaoued-Tej and Faical Bouazizi and Annick Valibouze},
	title = {Corrigendum: Algebraic certification of numerical algorithms computing Lagrange resolvents},
	journal = {Journal of Algebra and Its Applications}
}
```

**Comment by Stefan-Kohl** [comment]
@dimpase The corresponding reference on zbMATH likely also needs fixing then: https://zbmath.org/?q=an%3A1401.13009

**Comment by dimpase** [comment]
I wrote to the people concerned pointing it out; 

it seems that GAP does not use this zbMATH reference, thus it's up to them.

**Comment by alex-konovalov** [comment]
We take the data from MathSciNet. For now, until the corrigendum will appear in MathSciNet, I think the right approach would be to exclude MR3741064 from https://github.com/gap-system/GapWWW/blob/master/Doc/Bib/GapCite.MR and put the BiBTeX record above into https://github.com/gap-system/GapWWW/blob/master/Doc/Bib/GapCite.notyet.

**Comment by dimpase** [comment]
My understanding is that there will be no new paper, it's just the list of authors to MR3741064
that is corrected. What one can do is to correct that entry manually, and insert a note there pointing at the correction.

**Comment by alex-konovalov** [comment]
`GapCite.MR` is for MR numbers for entries that are retrieved automatically, so manual correction is equivalent to the action that I was describing above.

**Comment by fingolfin** [comment]
With the website relaunch in PR #339 we dropped the bib essentially (only providing the last version of the old .bib file but with no plans of adjusting it), which renders this issue moot.
