### ISSUE TITLE
LMS Short course on CGT in 2013

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GapWWW#122]
http://www-circa.mcs.st-and.ac.uk/cgt2013/lectures.shtml does not work any more. I have recovered the content and it is located on the host server where the GAP website is located. Need to put it somewhere to be available, preferably under the same URL. If not, make a part of  https://www.gap-system.org/Doc/Talks/talks.html.

**Comment by alex-konovalov** [comment]
The recovered content is not served, but stored at `/cs/home/gap-web/cgt2013` on the host server.

**Comment by alex-konovalov** [comment]
A repo for this is https://github.com/CIRCA-StAndrews/cgt2013, will now transfer it there.

**Comment by alex-konovalov** [comment]
This material is now available from https://circa-standrews.github.io/cgt2013/index.html

**Comment by alex-konovalov** [comment]
So all what remains to do it to update all links from GAP webpage to the new location.

**Comment by fingolfin** [comment]
I could not find any links matching this that need updating, or anything like that. Perhaps a `.ps` file links there?

So, any specific pointers? Otherwise we should just close this

**Comment by alex-konovalov** [comment]
@fingolfin I would add it to the list at https://www.gap-system.org/Doc/Talks/talks.html

**Comment by fingolfin** [comment]
With the website relaunch in PR #339 we dropped the talks page, which renders this issue moot.
