### ISSUE TITLE
Document technical setup of our website, in particular, where it is hosted

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#134]
Right now, I have no idea where our website is hosted, other than "In St Andrews", but not what server exactly, and where on that server. The only person that I know for sure to have this knowledge is @alex-konovalov. Perhaps @stevelinton and/or @ChrisJefferson also know or could at least find out. But in the spirit of <s>reducing</s> increasing our [bus factor](https://en.wikipedia.org/wiki/Bus_factor) I really think this should be written down somewhere, together with information on how to update the website.

There are some hints about updating the website in <https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/RELEASE_CHECKLIST.md>, but regarding the server, it just says that "you need to know how to access the host". Well, yeah, of course... :-)

I suggest we put this information into the README of this repository.

**Comment by Stefan-Kohl** [comment]
@fingolfin But according to the definition of the term given on the linked Wikipedia page, wouldn't it rather ENLARGE our bus factor if this information gets written down somewhere?

**Comment by fingolfin** [comment]
I am still hoping that @alex-konovalov will provide the information on which server the website is on...
