### ISSUE TITLE
Links in FAQ to David Joyner's website are broken

### ISSUE THREAD

**Issue by DominikBernhardt** [gap-system/GapWWW#140]
Under section 7 of the GAP FAQs we refer to two pages, one by David Joyner and one by Alexander Hulpke. Both links don't work at the moment.

UPDATE: Hulpke's links are now fixed.

**Comment by alex-konovalov** [comment]
@DominikBernhardt there are 12 questions there - could you provide their numbers or URLs please?

**Comment by alex-konovalov** [comment]
David Joyner's blog is now at https://yetanothermathblog.com/ - maybe one could find there new URLs.

**Comment by DominikBernhardt** [comment]
@alex-konovalov I think my remark is quite clear: Directly under section 7 in the FAQ, in the first bullet point, we reference David Joyner and in the second to Alexander Hulpke. Neither link currently works. I'm submitting a PR to fix the first bullet point, but the link on Alex' homepage is broken. So ping to @hulpke  :)

**Comment by hulpke** [comment]
I have had some mishap with my homepage as a side effect of working on different file systems and  having to change software due to OSX's new incompatibilities. I fear this material has gotten lost, so the link should go.

**Comment by fingolfin** [comment]
The material is still available in the wonderful Internet Archive, see <https://web.archive.org/web/20181111181354/http://www.math.colostate.edu/~hulpke/GAPQA/>

**Comment by alex-konovalov** [comment]
@DominikBernhardt ah, now clear. I read "Under section 7 of the GAP FAQs" as https://www.gap-system.org/Faq/faq.html#7 and clearly seen nothing there.

**Comment by wilfwilson** [comment]
This is related to #15.
