### ISSUE TITLE
Add FAQ about package versions

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GapWWW#147]
Q: Why the version of the package on the GAP website may be older than the version on the package's website?

A: The GAP website lists package versions included in the latest official GAP release. When a new version of a package is released, it is picked up for the redistribution with GAP, and will be included in the next GAP release subject to passing the tests. Only after that the GAP website will be updated to show the new version of the package.

**Comment by cdwensley** [comment]
Suggested rephrasing: 

Q: Why is the version of the package on the GAP website older than the version on the package's website?

A: The GAP website lists package versions included in the latest official GAP release. When a new version of a package is released, it is picked up for the redistribution with GAP, and will be included in the next GAP release subject to passing the tests. Only after that will the GAP website be updated to show the new version of the package.

**Comment by fingolfin** [comment]
I hope this is clearer with the new website, which explains this at the top of https://www.gap-system.org/packages/
