### ISSUE TITLE
Collect information and publish "Events" page

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GapWWW#149]
The page "Some Talks and Preprints" is really not reflecting the reality: https://www.gap-system.org/Doc/Talks/talks.html. It was neglected, and at some point sone patchy updates were placed on top of it as a quick fix. That does not display the reality. Also, it does not help to people interested to find where the will be new GAP related events in the word. A better sources in this sense are https://www.gapdays.de/ but it's limited to only one kind of GAP events. Another example of a good practice is https://wiki.sagemath.org/Workshops.

Please help me to collect information to illustrate the claim that GAP is used at various short training events (summer schools, workshops etc). around the world. I will then try to put these details on web, creating a new "Events" page, and listing events in reverse chronological order.

- All GAP Days from https://www.gapdays.de/
- All CoDiMa events from https://www.codima.ac.uk/training/ and https://www.codima.ac.uk/events/
- All events where GAP Software Carpentry lesson was taught: https://github.com/carpentries-incubator/gap-lesson/wiki
- Instructional workshop "Group algebras, representations and computation" (ICTS, Bangalore, India, October 2019) https://www.icts.res.in/program/garc2019 
- GAP-Singular meeting and school (PfalzAkademie, Lambrecht, Germany, from August 15 - August 23, 2019) https://opendreamkit.org/meetings/2019-04-02-GAPSingularMeeting/
-  Sage Days 102 at the University of Ibadan, Nigeria https://opendreamkit.org/2019/07/29/SageDays102/
- GAP in Algebraic Research Summer School: Nov 19 - 22, 2018, RWTH Aachen University https://lbfm-rwth.github.io/gap-in-algebraic-research-2018/
- Software Tools for Mathematics (Slovenia, September 2018) http://stm.famnit.upr.si/ 
- Software Tools for Mathematics (Mexico, January 2018) http://stm.famnit.upr.si/ 
- Summer School on Finite Geometry (Brighton, June 2017) https://ftmakroglu05.github.io/Finite-Geometry-School/
- Instructional workshop "Group theory and computational methods" (ICTS, Bangalore, November 2016) https://www.icts.res.in/program/GTACM16
- LMS Short course on CGT in St Andrews in 2013 (#122)
-  Summer school on computational group theory in Kirchberg/Hunsrück in 2011 http://www.math.rwth-aachen.de/~Graduiertenkolleg/schools/2011/
- Summer school "Groups Actions Computations 2010" in Allahabad, India https://www.icts.res.in/program/GAC2010
- Five RISC training schools in Symbolic Computation https://www3.risc.jku.at/projects/science/school/index.html

**Comment by alex-konovalov** [comment]
Future event, H/T @RussWoodroofe:
- G2G2-Summer School (Satellite event of the 8th European Congress of Mathematics, Slovenia, 2020) https://conferences.famnit.upr.si/event/13/

**Comment by pedritomelenas** [comment]
There was a software demo of numericalsgps in the imns 2008 meeting in Porto

https://cmup.fc.up.pt/cmup/ASA/numsgps_meeting/schedule_slides.html

and was also widely used in 

https://www.mathematik.uni-osnabrueck.de/en/news/conferencesworkshops/archive/normaliz_workshop_2015.html

Francy was presented in 

http://icms-conference.org/2018/sessions/session10/

**Comment by mohamed-barakat** [comment]
All examples at the end of this talk computed using GAP, CAP, and Singular:

https://www.newton.ac.uk/seminar/20200130091010001

**Comment by alex-konovalov** [comment]
YouTube has a collection of GAP videos:
- https://www.youtube.com/watch?v=kK2UcrZvnd0
- https://www.youtube.com/watch?v=c8ysQ_W6ALs
- https://www.youtube.com/watch?v=UYnbyVSlxnI

**Comment by Stefan-Kohl** [comment]
Somehow the links to some GAP talks on YouTube added here yesterday by @alex-konovalov seem to have got lost(?) -- here they are:

    https://www.youtube.com/watch?v=kK2UcrZvnd0
    https://www.youtube.com/watch?v=c8ysQ_W6ALs
    https://www.youtube.com/watch?v=UYnbyVSlxnI

**Comment by fingolfin** [comment]
With the website relaunch in PR #339 we dropped the talks page, which renders this issue moot.
