### ISSUE TITLE
Putting examples into Jupyter notebooks

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/GapWWW#150]
If anyone would like to have more practice with sharing reproducible computational experiments with GAP in Jupyter notebooks runnable on Binder, one could try to put there examples https://www.gap-system.org/Doc/Examples/examples.html using the tempate from https://github.com/rse-standrewscs/gap-binder-template

**Comment by ruthhoffmann** [comment]
@alex-konovalov I've just been going through the gapWWW issues, this one seems very similar to #98 .

**Comment by alex-konovalov** [comment]
Closed as a duplicate of #98 (thanks @ruthhoffmann)
