### ISSUE TITLE
Unify "Releases" / "Downloads" pages in Jekyll

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#163]
Compare e.g. these:
- https://www.gap-system.org/Releases/4.11.0.html
- https://www.gap-system.org/Releases/4.7.5.html
- https://www.gap-system.org/Releases/4.6.3.html

They look quite a bit different. 

On the other hand, the following two are very similar; but most of that similar content is created via "code duplication":
- https://www.gap-system.org/Releases/4.11.0.html
- https://www.gap-system.org/Releases/4.10.2.html

I would like to factor out more of the comment content, so that it doesn't have to repeated via copy&paste, and so that improvements also benefit older versions. But care has to be taken, in particular, watch out for these special cases with multiple package lists (we might want to split these packages into 2 resp. 3):
- https://www.gap-system.org/Releases/4.5.4.html
- https://www.gap-system.org/Releases/4.5.6.html

One idea for that: add `_includes/release_list_downloads.html` with a single argument, a list of file "records". Then render a table as shown on the most recent release pages (or perhaps improve on that "layout"). Then adapt all releases to use that include file; put the file lists into their front matter YAML.

For the remaining duplication, we have to be careful because not all releases have the same set of files, so we can't put it all in a single template. But we could have additional include files to help with that.

**Comment by wilfwilson** [comment]
I have gone some way to doing this; `_layouts/releases.html` now contains a lot more stuff that is shared, such that indeed now `_Releases/4.11.1.html` now contains _no_ custom content, and `_Releases/4.11.0.html` now only contains a little bit.

However, I have "backported" very little of this to earlier versions, so this issue is still very much open.
