### ISSUE TITLE
Broken link to "Choosing a License"

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#17]
I guess we should run a broken links checker on gap-system.org, and fix what we find...

One that I just stumbled over is that on <http://www.gap-system.org/Packages/Authors/authors.html>, it links to <http://sage.math.washington.edu/home/wdj/gap2007braunschweig/gap-package-licensing-info.html> in the section "Choosing a License", and that link is dead.

A modern alternative to that link might be <http://choosealicense.com/>

**Comment by alex-konovalov** [comment]
Thanks - I've replaced outdated link to http://choosealicense.com/ in https://github.com/gap-system/GapWWW/commit/96832d141baf7b3c6c83e2f704bfdbf20486759a. I will close this issue now since #15 is already about the same (see an update I've just posted there).
