### ISSUE TITLE
Move or remove `Download/feedback.html`

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#171]
That page is only referenced in one place, https://www.gap-system.org/Gap3/Download3/download.html -- so we could move it to the GAP3 page. Or we just remove it and kill that link (contrary to the ideal of preserving the old page; but ah well...)

**Comment by alex-konovalov** [comment]
Either fine with me. Formerly that page had a form. When forms were disabled, it was replaced by the text from that form. One day, we may set up some form again... but that can be done independently.

**Comment by fingolfin** [comment]
Was removed in PR #303
