### ISSUE TITLE
Copy missing data from https://www.gap-system.org/Download/Updates/index.html to CHANGES.md, then delete it

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#172]
On https://www.gap-system.org/Download/Updates/index.html we list changes for GAP 4.4 and 4.3 releases. As far as I can tell, the 4.4 changes are all already in the `CHANGES.md` file in the gap repository; but those for 4.3 are missing. We should copy that data to the `CHANGES.md` file.

Afterwards, we can remove the complete https://www.gap-system.org/Download/Updates/ directory -- possibly adding in a redirect to the CHANGES.md file. Not sure that's worth it, though, I'd be fine with just removing that data *shrug*.

**Comment by alex-konovalov** [comment]
Doing this now.

**Comment by alex-konovalov** [comment]
See PR https://github.com/gap-system/gap/pull/3926 which adds these release notes to `CHANGES.md`.

**Comment by alex-konovalov** [comment]
Closed by #182.
