### ISSUE TITLE
Overview of GAP capabilities for problems of different size

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GapWWW#18]
We need to have a page with a table describing GAP capabilities dependently on the type of the group (pc-group, permutation, finitely presented, matrix) and order of the group (or another metric like degree, dimension, etc.) to solve problems like calculation of conjugacy classes of elements, conjugacy classes of subgroups, and other canonical problems.

**Comment by alex-konovalov** [comment]
More details could tell something like "in this or that range, calculations normally take seconds/minutes/hours" and contain links to examples that may illustrate these statements.

**Comment by hungaborhorvath** [comment]
I agree, this is much needed.

**Comment by fingolfin** [comment]
While this is a nice idea at first glance, I think providing such data is highly non-trivial, I am not even sure it really is possible (these things do not just depend on the order of the group alone), but I'd be happy to be proven wrong if someone wants to create such a data collection.

However, I really think this is way out of scope for the GAP website. But regardless of that, we simply don't have the capacity to create or maintain such a thing.
