### ISSUE TITLE
Add back cities to names in some places (e.g. Council page)

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#198]
Looking at https://www.gap-system.org/Contacts/People/Council/council.html we see next to each name a place where that person is. In the Jekyll version https://test.gap-system.org/Contacts/People/Council/council.html this is gone. The same happened in other places.

Perhaps we should add this back, at least on the council page? There, it can be helpful for deciding who is in which GAP center, if any. Or maybe it's good to keep it away, to ensure we have less stuff to update...

Perhaps @lhsoicher as chair of the GAP council has an opinion on this, too?

**Comment by hulpke** [comment]
I think it makes sense to add places (or even institutions). This is the same what journals do.

**Comment by lhsoicher** [comment]
I agree with Alexander Hulpke.

________________________________________

**Comment by fingolfin** [comment]
Seems fine by me. Definitely something that should be addressed. Could be done during next GAP Days (whenever that will be), or by any volunteer.

We might also want to just add a hyperlink to the homepage for each name resp. name+city (when a homepage is known); I see no downside to that? 

Here is how I'd go about all that:
1. use the old data at https://github.com/gap-system/GapWWW/blob/0ad3452110abf370e107026d3efe15c596a9d164/lib/addresses for reference (but it's probably a good idea to check things for validity, e.g. are website URLs still correct? Is the person still in that place?)
2. edit `_data/namelink.yml` (and perhaps rename it, say to `_data/persons.yml` or so): instead of mapping each name to just an URL, map it to a map with more data; e.g. like this (I don't see a reason to keep city and country separate, so I'd just merge them, as in the author records of `PackageInfo.g` files)
```yaml
'Alexander Hulpke':
  url: 'http://www.math.colostate.edu/~hulpke/'
  place: "Fort Collins, USA"
```
 3. adapt `_includes/namelink.html` to match (e.g. `site.data.namelink[include.name]` -> `site.data.persons[include.name].url`, depending on what was done in step 2
4. either modify `namelink.html` to also include the place (then it'd appear everywhere we use it, for good and for worse); or else add a new include file doing so (say `personlink.html`? `nameplacelink.html` ? ... whatever)
5. Bonus points for modifying those include files to be flexible and dealing nicely with entries missing a URL and/or place (using conditionals in the template)
6. Finally modify `Contacts/People/Council/council.html` (and any other file where you think it makes sense) to use that include file; i.e. `{% include namelink.html name="Alexander Hulpke" %}` (or something else instead of `namelink.html`, depending on step 4)

**Comment by fingolfin** [comment]
Simpler solution: we just edit `Contacts/People/Council/council.md`

But it is not that straightforward for me what to do. What about former members who left academia, what do we put? Their last place of employment in academia? What about former members still in academia, do we keep tracking their employment indefinitely?

**Comment by hulpke** [comment]
I think it is task of council members to make us aware of affiliation changes,
