### ISSUE TITLE
Links to README files from package pages

### ISSUE THREAD

**Issue by hulpke** [gap-system/GapWWW#201]
Reported by Samuel Lelievre:

> By the way, the webpage for the "TransGrp" GAP package,
> 
>    https://www.gap-system.org/Packages/transgrp.html
> 
> has the following excerpt:
> 
> ### Online documentation
> 
> TransGrp: [ HTML] version   [ PDF] version
> 
> ### Download
> 
> [README]  ...
> 
> in which he links to the README and the HTML version
> of the documentation appear to be broken. 

I suspect part is the change from README to README.md which had been recommended to me.

**Comment by alex-konovalov** [comment]
@hulpke this seems to be a systematic problem for all packages. Perhaps an oversight while making switch to jekyll, @fingolfin ?

**Comment by fingolfin** [comment]
That seems likely, but your guess is as good as mine.

**Comment by fingolfin** [comment]
@ruthhoffmann and me just run into this again, and I checked: the files are there, the server simply refuses to transmit them. But I don't understand why; perhaps a server configuration issue (it may not like custom extensions like in `README.transgrp`).

If we can move the manuals into the GapWWW repo (see issue #223) then this would be easily resolved.

In any case, we are also discussing whether to provide these files *at all*; instead we are tempted to simply link to their counterparts on the package homepages.

**Comment by alex-konovalov** [comment]
Two considerations in favour of the existing way (i.e. providing these files):
- the package homepage may migrate or disappear, and the links will no longer be valid.
- the version on package homepage may be newer than the one redistributed with GAP.

**Comment by fingolfin** [comment]
In the meantime, we removed all these README links, so they are in particular all "fixed" this way... ;-)
