### ISSUE TITLE
Sync GAP support list members with listing on GAP website

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#202]
The page https://www.gap-system.org/Contacts/People/supportgroup.html should be synced with the actual people on the GAP support list. Possibly minus a few people who are just passive listeners -- although we really should wonder whether that makes sense, as it is also somewhat of a trust issue, i.e. people who write to the GAP support list might be conscious about who will read their emails, and might take a look at those lists... 

At the very least, we shouldn't list people on the website who are not anymore on the support mailing list (e.g. Max Neunhöffer).

People who can provide (and edit) the current list of subscribes include @alex-konovalov and myself.

**Comment by Stefan-Kohl** [comment]
The following people are not currently listed on the website, but do read mail to the GAP support list:

Alice Niemeyer
Reimer Behrends
Dominik Bernhardt
Bill Allombert
Chris Wensley
Chris Jefferson
Colva Roney-Dougal
Gabor Horvath
Jürgen Müller
Markus Pfeiffer
Martin Schönert
Mike Newman
Robert Morse
Charles Wright

The following people are currently listed on the website, but do (apparently) not read mail to the GAP support list:

Greg Gamble 
Steve Linton
Max Neunhöffer
Jack Schmidt
