### ISSUE TITLE
Remove https://www.gap-system.org/Download/INSTALL

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#206]
It is outdated, and thus potentially dangerous.

We could either just remove it; or replace it with a page that links to the actual instructions....

See also discussion on https://github.com/gap-system/gap/pull/4168

**Comment by alex-konovalov** [comment]
Indeed, we link now directly to the version tagged with the release, e.g. to https://github.com/gap-system/gap/blob/v4.11.0/INSTALL.md from https://www.gap-system.org/Releases/4.11.0.html. It should just be deleted.
