### ISSUE TITLE
Fix HAPprime links

### ISSUE THREAD

**Issue by slel** [gap-system/GapWWW#214]
There are a few broken links concerning the HAPprime GAP package.

As far as I understand:

- HAPprime development stopped in 2011
- the last released version is 0.6dev, released 2011-06-09
- correct links for HAPprime are as follows:
  - home: [0] https://gap-packages.github.io/happrime/
  - repo (archived): [1] https://github.com/gap-packages/happrime
  - docs (for 0.5.1): [2] https://www.gap-system.org/Manuals/pkg/happrime/doc/userguide/chap0.html

The page [3] https://www.gap-system.org/Packages/packages.html mentions
HAPprime but links to [4] https://www.gap-system.org/Packages/happrime.html
(which gives `404 Not Found`) instead of linking to [0]. This can be fixed by editing:
https://github.com/gap-system/GapWWW/blob/b373b2cdb3fbc7e504d905e00b6cb9029df80819/Packages/packages.html#L137
Alternatively, set up a redirection from [4] to [0], or restore a page at [4],
stating the package is archived and linking to its home [0] and its archived repo [1].

The page [5] https://gap-packages.github.io/ no longer mentions HAPprime
since the following commit special-cased it to not be listed:
https://github.com/gap-packages/gap-packages.github.io/commit/faefd3642618976a502871cf42c3cadd1db0a16a#diff-a48746cae70c44e7e105b594aad338ddd105c93c1cb445a40ba6aab785ba69e5

The home page [0] has a link from the words "the package manual" to
[6] https://gap-packages.github.io/happrime/doc/userguide/chap0.html
which gives `404 Not Found`. It should probably link to [2] instead.
It also has a link from the author's name to his former webpage (also 404),
which should probably be instead link to an archived version of one of his
former webpages:
[7] http://web.archive.org/web/20110922213701/http://www.cs.st-andrews.ac.uk/~pas
[8] https://web.archive.org/web/20080520194102/http://www.maths.nuigalway.ie/~pas/

Changing these links at [6] probably requires editing
[9] https://github.com/gap-packages/happrime/blob/master/PackageInfo.g
which is presumably hard, now that the repository is archived.

**Comment by fingolfin** [comment]
Somehow missed this issue before... Anyway: we don't want any links to https://gap-packages.github.io/happrime/ -- to the contrary, I've now deleted (or rather, unpublished) that page. The link to https://github.com/gap-packages/happrime has been removed. I think that resolves it all.

**Comment by slel** [comment]
Thanks for taking care of this. What triggered me into opening this was

- [Ask Sage question 55375](https://ask.sagemath.org/question/55375)

which was about the function `ResolutionPrimePowerGroupRadical`.

Part of HAPPrime made it into HAP. That function may or may not have.
But this is not the place to discuss that.
