### ISSUE TITLE
Better handling of withdrawn packages

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#229]
To mark PolymakeInterface as withdrawn, I had to ...
1. remove `_Packages/polymakeinterface.html`
2. add `Packages/polymakeinterface.html`
3. add an entry at the bottom of `Packages/packages.html`

The update scripts should detect if a package was removed and take care of point 1 (see also issue #217).

For 2+3, I think there should be a YAML file somewhere with the explanation for why the package is gone, and then this should be used to generate the page for point 2, and the entry for point 3.

This YAML file should also be generated by the update script, with some generic message ("this package has been withdrawn from distribution"); a human can optionally edit it later on.

**Comment by wilfwilson** [comment]
Agreed.

**Comment by wilfwilson** [comment]
The first of these is now done.

**Comment by fingolfin** [comment]
This should also be documented. We need a central place (e.g. the README.md in this repository) where we document "how to withdraw a package from the website".

**Comment by fingolfin** [comment]
With the new website the procedure is to add the package to `about/history/oldpkgs.md`. Nothing else needs to be done.

This event is rare enough and the action simple enough that I don't think we need to worry about it anymore. If a future event proves me wrong (i.e. we mess it up) then it's still time to think about a mitigation *that would have prevented that particular failure*
