### ISSUE TITLE
F.A.Q. entry on generating sets on groups

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GapWWW#23]
There may be a useful answer added to https://github.com/gap-system/GapWWW/blob/master/Faq/faq.mixer, based on:
- https://github.com/gap-system/gap/issues/929
- http://math.stackexchange.com/questions/1396128/need-a-3-group-with-3-generators
- http://math.stackexchange.com/questions/1618446/how-can-i-display-generators-or-a-minimal-generating-set-with-gap

**Comment by fingolfin** [comment]
I don't see what sets this apart from many other "false believes" beginners in math have about everything? I'd rather cut down our FAQ further then add much to it; but if someone really things this would be a worthwhile addition, I'd be willing to merge such a PR. But I don't think it makes sense to keep this open after 8 years in which nobody seems to have cared sufficiently about this to bother :-)
