### ISSUE TITLE
Enhancement: show basic package statistics

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#232]
On https://www.gap-system.org/Packages/packages.html we could show information along the lines of:

"There are currently NNN packages shipped with GAP, of these YYY have been accepted."

(BTW, quite some of these packages have their `Status` field still set to `dev`, not to `deposited`, may want to follow up on that with their maintainers)

**Comment by wilfwilson** [comment]
This should be easy to compute from the relevant file in the `_data/package-infos/` directory now.

**Comment by fingolfin** [comment]
Total number of packages is now shown with the website relaunch in PR #339 while we abolished the concept of "accepted" packages so the second point is moot.
