### ISSUE TITLE
Link to gap-4.11.1.exe on 4.11.1 release page

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/GapWWW#239]
This file is ~~imminently~~ available at https://github.com/gap-system/gap/releases/tag/v4.11.1

And should be linked to, along with some text, at https://www.gap-system.org/Releases/4.11.1.html

**Comment by fingolfin** [comment]
So someone needs to edit https://github.com/gap-system/GapWWW/blob/master/_Releases/4.11.1.html accordingly
