### ISSUE TITLE
update of the GAP bibliography

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/GapWWW#243]
The file [gap-publishednicer.bib](http://www.gap-system.org/Doc/Bib/gap-publishednicer.bib) available from the GAP website has not been updated since August 2020. Would it make sense to update this file automatically with each GAP release?
(The current version is outdated not only w.r.t. the contents but also w.r.t. the markup used to represent special characters. When the current GAPDoc version is used to process the source data then the result is nicer.)

**Comment by alex-konovalov** [comment]
I have also discovered that https://www.gap-system.org/Doc/Bib/bib.html has no link to PDF version any more, but `convbib.g` still builds it as described at https://github.com/gap-system/GapWWW/tree/master/Doc/Bib and trips over LaTeX irregularities present in MathSciNet bib entries. That code should be removed, and that will hopefully make easier to automate the rendering of the code above.

**Comment by ThomasBreuer** [comment]
@alex-konovalov I do not catch the point.
My understanding was that adding new entries requires some interaction, in order to adjust the conversion code to unexpected LaTeX syntax in the new entries (the old entries should not cause problems, due to earlier adjustments).
Only after that, the conversion to HTML can be done automatically and will yield a reasonable result, and also the improved `.bib` file that we offer can be processed by LaTeX.

**Comment by fingolfin** [comment]
Resolved by PR #339 which did the new site design and dropped most of our custom bib
