### ISSUE TITLE
Update `Packages/Contrib/cliffordmatrices.html`

### ISSUE THREAD

**Issue by wilfwilson** [gap-system/GapWWW#251]
https://www.gap-system.org/Packages/Contrib/cliffordmatrices.html is referenced from the paper "The Character Table of 2_+^{1+22}.Co_2", which is available from e.g. https://core.ac.uk/download/pdf/82057605.pdf

Therefore we can't reasonably delete or move this page (although we could provide a redirect), but this page could be updated (such as: changing the reference from "to appear" to the actual reference).

**Comment by fingolfin** [comment]
Agreed.

**Comment by fingolfin** [comment]
Resolved by PR #339 which did the new site design and dropped this particular subpage
