### ISSUE TITLE
Links on https://www.gap-system.org/Doc/manuals.html all not working

### ISSUE THREAD

**Issue by veni-vidi-code** [gap-system/GapWWW#252]
Most links on https://www.gap-system.org/Doc/manuals.html for the package docs links give a 404 page. Removing the version number from the provided links makes them work. I am not sure what exactly leads to this problem, if they are misslinked o manual.html or if they are provided on the wrong url.

(E.g. https://www.gap-system.org/Manuals/pkg/images-1.3.0/doc/chap0.html is linked but https://www.gap-system.org/Manuals/pkg/images/doc/chap0.html works)

**Comment by veni-vidi-code** [comment]
Are maybe src and dist swapped in https://github.com/gap-system/GapWWW/blob/master/etc/extract_manuals.py?

**Comment by wilfwilson** [comment]
Thanks for the report, I've developed a fix in #253.

The `extract_manuals.py` is as intended, I believe. For now, we have decided to not use version numbers in the URLs of the manuals, so `.../pkg/PACKAGENAME/doc/...` will always give the most up-to-date manual. We are considering whether and how to offer a more modern way of giving versioned manuals.
