### ISSUE TITLE
Update instructions for subscribing to the GAP Forum

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#270]
We should update the instructions on <https://www.gap-system.org/Contacts/Forum/forum.html> to describe how to subscribe by email, as the webinterface is still down.

(And once the mailing list software switches, we should update it again)

**Comment by hongyi-zhao** [comment]
In fact, I figured out the subscribe method described [here](https://www.mail-archive.com/forum@gap-system.org/info.html):

> List Subscribe:
> https://mail.gap-system.org/mailman/listinfo/forum, mailto:forum-request@gap-system.org?subject=subscribe

**Comment by fingolfin** [comment]
Thanks @hongyi-zhao for looking it up. I've made PR #271 to deal with it.
