### ISSUE TITLE
Hosting GAP packages and developer's pages

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/GapWWW#28]
There are two directories in this repository 
- https://github.com/gap-system/GapWWW/tree/master/HostedGapPackages 
- https://github.com/gap-system/GapWWW/tree/master/DevelopersPages 

As their README say,
- `HostedGapPackages` is the directory to publish packages which are temporary maintained by us (for example, is the author is no longer maintaining the package, and a small adjustment of the package is needed, which may not require finding a new maintainer).
- `DevelopersPages` is the directory to keep pages of GAP developers asking us to host them (for example, when moving from one institution to another), in particular, to be able to make available new versions of their packages. 

`HostedGapPackages` contains websites for `pargap` and `singular` packages, and also for the `if` package (not redistributed with GAP any more), and `DevelopersPages` hosts @Stefan-Kohl's homepage.

The content of these directories is a not a part of the GAP website which is kept under the CVS control, but just an additional section stored in a separate location and made available at `www.gap-system.org/...` due to an alias at `httpd.conf`.

This setup is fragile, and it recently became broken after GAP website moved to another server. Trying to fix it, I am hesitating to use any hacks which _will_ break later again. I think that the right way to go now would be creating GitHub repositories and associated websites for packages, and recommending package authors to use [GitHub pages](https://help.github.com/articles/what-is-github-pages/) to publish their websites there (see also [this](https://help.github.com/articles/user-organization-and-project-pages/). I am more than happy to help with this.  We can then setup a redirect for appropriate URLs from gap-system.org then.

The checklist to track the progress of this is below:

- [x] @Stefan-Kohl's homepage
- [x] pargap
- [x] if
- [x] singular

**Comment by fingolfin** [comment]
First question: Do we have backups of the old pages, in particular of the websit of @Stefan-Kohl ? I hope so, but it does not become clear from what you write here.

Next, I fully agree -- the three packages could be moved to the `gap-packages` organization. For pargap, I think @alex-konovalov is a co-maintainer and thus could do it (I am happy to help, too ;-). For the other two, somebody needs to contact the maintainers -- @alex-konovalov can you do that?

As to the homepage of @Stefan-Kohl : No offense, but I don't think we should be hosting people's homepage. We are not web providers, and I wouldn't want to be responsible for safekeeping somebody else's web presence. Perhaps it made some limited sense year ago. But today, there are countless free or cheap options out there to host personal webpages. Be it on GitHub Pages or with GitLab or rent a cheap webspace (starting at less than 1 euro/month in Germany). We can assist @Stefan-Kohl with the move, and of course adding a redirect is no problem either (as it requires no further maintenance).

**Comment by alex-konovalov** [comment]
1. yes, we have @Stefan-Kohl's website, and he should be able to access the directory as well. It's simply not visible from the new hosting of `GapWWW`.
2. yes, I will be able to handle packages in due course, although not in a hurry.
3. yes, I agree - we are having private discussion with @Stefan-Kohl at the moment.

**Comment by alex-konovalov** [comment]
I've ticked Stefan's box above: the new homepage is https://stefan-kohl.github.io/ and a redirect has been configured.

**Comment by alex-konovalov** [comment]
Ticked the box for Singular - it's now moved to https://gap-packages.github.io/singular/

**Comment by alex-konovalov** [comment]
The `if` package is no longer redistributed with GAP. It's last version is available at https://www.gap-system.org/Packages/if.html. Ticked the box too.

**Comment by alex-konovalov** [comment]
So, we need to wrap up this issue before closing - setting up redirects, archive directories, etc.

**Comment by fingolfin** [comment]
Actually, `if` does not seem to be available on https://www.gap-system.org/Packages/if.html -- all links on that page (outside the navbar, of course) are dead. Including those to tarballs and the manual.

**Comment by alex-konovalov** [comment]
Old archives are at https://www.gap-system.org/pub/gap/gap44/tar.gz/packages/. Those links that come from it's last published PackageInfo.g are of course broken. There is no `if.mixer` mixer file any more, that page simply should not exist - will delete it.

**Comment by fingolfin** [comment]
@alex-konovalov can we close this? If not, can you explain what needs to be done, concretely? I'd do it, but I  couldn't figure out *what* from reading the comments here.
