### ISSUE TITLE
Restore https://test.gap-system.org

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#306]
This used to be a staging ground where one could test changes before having them actually go live. This should be revived, possibly tied to a branch of its own (e.g. `staging` or `test` or whatever).

I can in principle take care of this, by following the steps used to set it up for the `master` branch and outlined in `etc/README.server.md` but I need to find the time, plus perhaps it would be wise to have at least one other person become familiar with this setup, if there are any volunteers...

**Comment by ruthhoffmann** [comment]
This has been done under  [https://dev.gap-system.org](https://dev.gap-system.org) which reflects the `dev` branch.
