### ISSUE TITLE
Change web server to rewrite URLs into canonical form

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#31]
Right now, the GAP homepage is reachable under at least the following addresses:
* https://gap-system.org/
* https://www.gap-system.org/
* https://gapsystem.org/
* https://www.gapsystem.org/

There might be more (e.g. under the St Andrews domain?).

There is nothing wrong with that, but it can be confusing for users. I think we should pick one, and then configure the webserver to automatically redirect any requests for the others to the canonical one. My personal pick would be https://www.gap-system.org/

**Comment by alex-konovalov** [comment]
The following now give a 301 redirect to https://www.gap-system.org:
- http(s)://gapsystem.org
- http(s)://www.gapsystem.org
- http(s)://gap-system.org
