### ISSUE TITLE
editing `gap-publishednicer.bib`?

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/GapWWW#322]
Recently I noticed (when preparing a release of the Browse package) that some entries in the file `Doc/Bib/gap-publishednicer.bib` have changed, but no new entries have been added.
Thus I think that the changes are due to editing by hand. (The file seems to be too large for the github web interface.)

As far as I understand, most of `Doc/Bib/gap-publishednicer.bib` is created automatically from MathSciNet data, and the recent changes did not come from there.
Shall we really change links in these data by hand at all, and if yes, what happens after updates from MathSciNet?

**Comment by fingolfin** [comment]
Indeed, the file was modified as part of me running a bunch of scripts to update broken URLs and/or change http to https, on the whole repository. I just did not think about the fact that some of these files are generated. So indeed, the next time someone (who??) re-runs these scripts, these changes will be lost. That's bad.

So one option would be to undo all these changes.

But perhaps nicer would be to codify the changes that were made and perform them as part of the update process?

BTW I notice there is a script `Doc/Bib/fixes.sh` which is not mentioned nor called, ever.  Perhaps @alex-konovalov knows what it is for / from?

**Comment by alex-konovalov** [comment]
I know, as I have created it - see commit message and comment there. I was calling it manually. 

I really need to update GAP bibliography one day this year...

**Comment by fingolfin** [comment]
Resolved by PR #339 in so far as we do not plan to update this file further.
