### ISSUE TITLE
Provide SHA-1 and/or SHA256 (or more) instead of MD5

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#34]
MD5 is not safe anymore. SHA-1 is better, though also in the process of falling.

**Comment by alex-konovalov** [comment]
OK - will do for GAP 4.9 or GAP 4.8.8 whichever happens earlier.

**Comment by alex-konovalov** [comment]
Used sha256 for GAP 4.8.8: https://github.com/gap-system/GapWWW/pull/40/commits/e2611fa037f702c5f813fa1464440257bfe76e5a
