### ISSUE TITLE
Bad (or at least not optimal) HTTP Content-Type for plain text files

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#35]
When one clicks on "INSTALL" on e.g. the page http://www.gap-system.org/Releases/4.8.6.html this file is transmitted with MIME type `application/octet-stream`, which cause the browser to download it (resp. offer to download it). It would be much better if it was transferred with content type  `text/plain;charset=utf-8`such that it is displayed in the browser.

Similar problems affect other files, e.g. `README`, and on other pages.

**Comment by alex-konovalov** [comment]
@fingolfin I think this is to be set in nginx configuration - will investigate. The same BTW happens with PackageInfo.g files hosted on GitHub.

**Comment by alex-konovalov** [comment]
yes, there is something that should be fixed. On macos, it may be even more confusing:

![screen shot 2018-01-27 at 22 44 47](https://user-images.githubusercontent.com/5751387/35477084-e2f76100-03b3-11e8-8a04-6d20e9d7480b.png)

The problem with INSTALL/INSTALL.md will be fixed by #66 in a different way.

**Comment by alex-konovalov** [comment]
@fingolfin install files are now handled in #66, and all package README files are now handled properly. Could you please check if there are any other files which still have to be tweaked, or close this issue, if there are none?

**Comment by alex-konovalov** [comment]
This seems to work fine. If @fingolfin or anyone else will find other files, please post them here and reopen this issue.
