### ISSUE TITLE
missing whitespace on many pages

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-system/GapWWW#370]
Whitespace is often missing immediately before links, see for example [the page about groups](https://www.gap-system.org/capabilities/groups).

**Comment by fingolfin** [comment]
MIght be the same issues as described in PR https://github.com/gap-system/GapWWW/pull/369 which I just merged ?

**Comment by ThomasBreuer** [comment]
Yes. (I had searched only for issues with the word "whitespace", not for pull requests.)
