### ISSUE TITLE
Mention PackageMaker in suggestions to package authors  

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/GapWWW#38]
https://www.gap-system.org/Packages/Authors/authors.html mentions Example package but not the PackageMaker

**Comment by alex-konovalov** [comment]
@fingolfin would you be able to provide some text please? If you don't want to write in for Mixer, Markdown here will suffice.

**Comment by fingolfin** [comment]
I am not sure what you want to do, so how would I know what to write?

If you just want to tell people about PackageMaker, you could just say something like "There is also tool called [PackageMaker](...link...) which creates a bare-bones package for you. For details, refer to its documentation."

**Comment by alex-konovalov** [comment]
I've asked you in which terms you'd like to mention it. Thanks, that suffices then. I will add a text like this (I will only replace "bare-bones" by actual explanation what does that mean, since that may be non-obvious).

**Comment by fingolfin** [comment]
OK.
