### ISSUE TITLE
Remove non-working validator form

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#49]
The form on http://www.gap-system.org/Packages/validator.html does not work anymore, as Frank discontinued this service. Let's remove it?

**Comment by alex-konovalov** [comment]
But I've deleted `Packages/validator.mixer` in https://github.com/gap-system/GapWWW/commit/235ad4cc6f2eddf452b3240b80723c743d6a3491 ... oh, wait, the generated html file is still there, and while I've removed links to it, you might have it bookmarked somewhere. Deleted html file now.
