### ISSUE TITLE
Broken link to changes manual on https://www.gap-system.org/Download/Updates/index.html

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#68]
On https://www.gap-system.org/Download/Updates/index.html we have a link to

https://www.gap-system.org/Download/Manuals/doc/changes/chap0.html

but that gives a 404. Correct links:

https://www.gap-system.org/Manuals/doc/changes/chap0.html

**Comment by alex-konovalov** [comment]
Fixed (missing one level in relative path)
