### ISSUE TITLE
Improve links to "changes" on download pages

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#69]
For each GAP release, we have a separate download page, with a link to a list of changes, like
> see the overview of changes between GAP 4.8.9 and GAP 4.8.8 here
where `here` is a hyperlink. For the GAP 4.8 releases, this hyperlink is always http://www.gap-system.org/Manuals/doc/changes/chap2.html#X78E4871E83067AB2

Which goes to the top of the changes file. Which is usually not where the promised information is; the user has to scroll / search.

This is because the link is generated with this mixer code in each case:
```
<mixer manual="Changes: Changes between GAP 4.7 and GAP 4.8">here</mixer>).
```
I think that if we instead reference the exact release, we'd get a link directly to the relevant subsection:
```
<mixer manual="Changes: GAP 4.8.9 (December 2017)">here</mixer>).
```
I'd only retain the "generic" link to the top of the page resp. chapter for the first public release of the series, i.e. GAP 4.8.2 was the first public release of the GAP 4.8 series, so it should list all changes since 4.7.x. 

Alternatively, we could provide two links:  "To see all changes between 4.8.8 and 4.8.9 click here; to see al changes since GAP 4.7, see here."

**Comment by alex-konovalov** [comment]
I will take this into account when we will be releasing 4.9.2. There might be some merit in visiting previous GAP 4.5 - 4.8 release pages and updating these links too, but that seem to be a "wontfix" task for me.

**Comment by alex-konovalov** [comment]
This is now superseded by #153, because the Changes manual does no longer exist.
