### ISSUE TITLE
GAP Authors

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GapWWW#70]
http://www.gap-system.org/Contacts/People/authors.html says:

"For all authors the contributions can be identified from the header of the library or kernel files. If you want to find the contributions of a particular author you should grep the library and kernel files searching for the full name (first name and family name but no title) of the respective author"

- is this still true? Some files may have names, but this does not seem to be the rule still followed any more.

Also, while GAP revisions history prior to the move to GitHub contains generic `gap` commits, we can mention that in addition to this list, contributors after the move to GitHub may be seen from the revisions history.

**Comment by alex-konovalov** [comment]
Cf. https://github.com/gap-system/gap/pull/3092

**Comment by fingolfin** [comment]
How about replacing that page with a link to https://github.com/gap-system/gap/blob/master/COPYRIGHT.

**Comment by alex-konovalov** [comment]
@fingolfin that would look perfect to me. We should also check for any new names to be added to the `COPYRIGHT` file.
