### ISSUE TITLE
"Changes" manual and the website 

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/GapWWW#71]
See https://github.com/gap-system/gap/issues/2150 - posting here for cross-ref. @fingolfin wrote there:

> Another things I find confusing is that the GAP website lists descriptions of changes in GAP releases in multiple places:

* the changes manual
* the "Release history " page, a bit hidden away under http://www.gap-system.org/Download/Updates/index.html
* the "History" page, at http://www.gap-system.org/Doc/History/history.html

> Of these, I feel that we could at least eliminate the "Release history" page, by merging it into the changes manual. The 4.4.x series seems to already be in the changes manual, so we "only" would have to transfer the entries for the GAP 4.3 bugfix releases. Afterwards, we could delete the pages (and perhaps in their place leave little HTML files which forward to the new locations in the changes manual, but without appearing in the site navigation).

**Comment by alex-konovalov** [comment]
This is relevant to work in progress by @dimpase in https://github.com/gap-system/gap/pull/3886, which  Changes manuals book into markdown.

**Comment by fingolfin** [comment]
Yeah, the changes manual is gone.

Further progress was made during virtual GAP Days Spring 2020: We removed <https://www.gap-system.org/Download/Updates/index.html>. Also the history page now links to CHANGES.md

It's not quite perfect yet, but good enough for me to close this. Further improvements will have to be made in the coming months as we clean up the website further.
