### ISSUE TITLE
Remove or replace outdated PackageInfo.g

### ISSUE THREAD

**Issue by fingolfin** [gap-system/GapWWW#75]
On https://www.gap-system.org/Packages/Authors/authors.html there is a link to an old version of the example `PackageInfo.g`. This file comes from the GapWWW repository. We should either replace it with a current version, or (perhaps better) remove it entirely (and perhaps link to the GitHub repo of the example package? Or directly mention `PackageMaker`, instead of doing it two paragraphs later?

**Comment by alex-konovalov** [comment]
Good catch. I will remove it entirely and will link to the package. Plus mention PackageMaker.

**Comment by fingolfin** [comment]
Thanks. Note that PackageMaker is already mentioned, just a bit later
